// To test the empty state, temporarily set one category's `rows` to an empty array []

export type Outcome = 'win' | 'loss' | 'over' | 'under' | 'push' | 'bonus' | 'none'

export interface LeaderboardRow {
  rank: number
  team: string
  teamColor: string
  count: number
  totalGames: number
  outcomes: Outcome[]
}

export interface LeaderboardCategory {
  id: string
  label: string
  countUnit: string
  metaUnit: string
  rows: LeaderboardRow[]  // length 30, sorted by count descending
}

function buildOutcomes(target: Outcome, count: number, others: Outcome[]): Outcome[] {
  const total = 28
  const arr: Outcome[] = []
  let ti = 0
  let oi = 0
  for (let i = 0; i < total; i++) {
    const oRemaining = (total - count) - oi
    if (ti < count && (oRemaining === 0 || Math.round(ti * total / count) <= i)) {
      arr.push(target)
      ti++
    } else {
      arr.push(others[oi % others.length])
      oi++
    }
  }
  return arr
}

function buildEmpty(others: Outcome[]): Outcome[] {
  const arr: Outcome[] = []
  for (let i = 0; i < 28; i++) arr.push(others[i % others.length])
  return arr
}

// ─── Team color map ───────────────────────────────────────────────────────────

const C = {
  Yankees:       '#003087',
  Dodgers:       '#005A9C',
  Astros:        '#002D62',
  RedSox:        '#BD3039',
  Braves:        '#CE1141',
  Cubs:          '#0E3386',
  Mets:          '#FF5910',
  Padres:        '#2F241D',
  Phillies:      '#E81828',
  Giants:        '#FD5A1E',
  Mariners:      '#0C2C56',
  Cardinals:     '#C41E3A',
  Brewers:       '#FFC52F',
  Rangers:       '#003278',
  Twins:         '#002B5C',
  Rays:          '#092C5C',
  BlueJays:      '#134A8E',
  Orioles:       '#DF4601',
  Diamondbacks:  '#A71930',
  Guardians:     '#00385D',
  Athletics:     '#003831',
  Royals:        '#004687',
  Tigers:        '#0C2340',
  WhiteSox:      '#27251F',
  Pirates:       '#FDB827',
  Reds:          '#C6011F',
  Rockies:       '#33006F',
  Nationals:     '#AB0003',
  Marlins:       '#00A3E0',
  Angels:        '#BA0021',
}

// ─── LEADERBOARD ─────────────────────────────────────────────────────────────

export const LEADERBOARD: LeaderboardCategory[] = [

  // ─── 1. Most Overs — TIE at rank 2 between Braves & Yankees (per spec) ───
  {
    id: 'most-overs',
    label: 'Most Overs',
    countUnit: 'OVERS',
    metaUnit: 'OUT OF 28 GAMES',
    rows: [
      { rank: 1,  team: 'Los Angeles Dodgers',   teamColor: C.Dodgers,      count: 22, totalGames: 28, outcomes: buildOutcomes('over', 22, ['under','push','under','under']) },
      { rank: 2,  team: 'Atlanta Braves',         teamColor: C.Braves,       count: 20, totalGames: 28, outcomes: buildOutcomes('over', 20, ['under','push','under']) },
      { rank: 2,  team: 'New York Yankees',       teamColor: C.Yankees,      count: 20, totalGames: 28, outcomes: buildOutcomes('over', 20, ['under','under','push','under']) },
      { rank: 4,  team: 'Philadelphia Phillies',  teamColor: C.Phillies,     count: 18, totalGames: 28, outcomes: buildOutcomes('over', 18, ['under','push','under']) },
      { rank: 5,  team: 'Tampa Bay Rays',         teamColor: C.Rays,         count: 17, totalGames: 28, outcomes: buildOutcomes('over', 17, ['under','under','push']) },
      { rank: 6,  team: 'Boston Red Sox',         teamColor: C.RedSox,       count: 16, totalGames: 28, outcomes: buildOutcomes('over', 16, ['under','push','under']) },
      { rank: 7,  team: 'Houston Astros',         teamColor: C.Astros,       count: 15, totalGames: 28, outcomes: buildOutcomes('over', 15, ['under','under','push']) },
      { rank: 8,  team: 'Chicago Cubs',           teamColor: C.Cubs,         count: 15, totalGames: 28, outcomes: buildOutcomes('over', 15, ['under','push','under','under']) },
      { rank: 9,  team: 'Toronto Blue Jays',      teamColor: C.BlueJays,     count: 14, totalGames: 28, outcomes: buildOutcomes('over', 14, ['under','push','under']) },
      { rank: 10, team: 'Seattle Mariners',       teamColor: C.Mariners,     count: 13, totalGames: 28, outcomes: buildOutcomes('over', 13, ['under','under','push']) },
      { rank: 11, team: 'Minnesota Twins',        teamColor: C.Twins,        count: 13, totalGames: 28, outcomes: buildOutcomes('over', 13, ['under','push','under']) },
      { rank: 12, team: 'San Diego Padres',       teamColor: C.Padres,       count: 12, totalGames: 28, outcomes: buildOutcomes('over', 12, ['under','push']) },
      { rank: 13, team: 'San Francisco Giants',   teamColor: C.Giants,       count: 12, totalGames: 28, outcomes: buildOutcomes('over', 12, ['under','under','push']) },
      { rank: 14, team: 'Texas Rangers',          teamColor: C.Rangers,      count: 11, totalGames: 28, outcomes: buildOutcomes('over', 11, ['under','push','under']) },
      { rank: 15, team: 'Cleveland Guardians',    teamColor: C.Guardians,    count: 11, totalGames: 28, outcomes: buildOutcomes('over', 11, ['under','under','push','under']) },
      { rank: 16, team: 'Milwaukee Brewers',      teamColor: C.Brewers,      count: 10, totalGames: 28, outcomes: buildOutcomes('over', 10, ['under','push','under']) },
      { rank: 17, team: 'Baltimore Orioles',      teamColor: C.Orioles,      count: 10, totalGames: 28, outcomes: buildOutcomes('over', 10, ['under','under','push']) },
      { rank: 18, team: 'St. Louis Cardinals',    teamColor: C.Cardinals,    count: 9,  totalGames: 28, outcomes: buildOutcomes('over', 9,  ['under','push','under']) },
      { rank: 19, team: 'Arizona Diamondbacks',   teamColor: C.Diamondbacks, count: 9,  totalGames: 28, outcomes: buildOutcomes('over', 9,  ['under','under','push']) },
      { rank: 20, team: 'New York Mets',          teamColor: C.Mets,         count: 8,  totalGames: 28, outcomes: buildOutcomes('over', 8,  ['under','push','under']) },
      { rank: 21, team: 'Kansas City Royals',     teamColor: C.Royals,       count: 8,  totalGames: 28, outcomes: buildOutcomes('over', 8,  ['under','under','push']) },
      { rank: 22, team: 'Oakland Athletics',      teamColor: C.Athletics,    count: 7,  totalGames: 28, outcomes: buildOutcomes('over', 7,  ['under','push','under']) },
      { rank: 23, team: 'Detroit Tigers',         teamColor: C.Tigers,       count: 7,  totalGames: 28, outcomes: buildOutcomes('over', 7,  ['under','under','push']) },
      { rank: 24, team: 'Cincinnati Reds',        teamColor: C.Reds,         count: 7,  totalGames: 28, outcomes: buildOutcomes('over', 7,  ['under','push','under','under']) },
      { rank: 25, team: 'Pittsburgh Pirates',     teamColor: C.Pirates,      count: 6,  totalGames: 28, outcomes: buildOutcomes('over', 6,  ['under','push','under']) },
      { rank: 26, team: 'Washington Nationals',   teamColor: C.Nationals,    count: 6,  totalGames: 28, outcomes: buildOutcomes('over', 6,  ['under','under','push']) },
      { rank: 27, team: 'Chicago White Sox',      teamColor: C.WhiteSox,     count: 6,  totalGames: 28, outcomes: buildOutcomes('over', 6,  ['under','push','under']) },
      { rank: 28, team: 'Colorado Rockies',       teamColor: C.Rockies,      count: 6,  totalGames: 28, outcomes: buildOutcomes('over', 6,  ['under','under','push','under']) },
      { rank: 29, team: 'Miami Marlins',          teamColor: C.Marlins,      count: 6,  totalGames: 28, outcomes: buildOutcomes('over', 6,  ['under','push']) },
      { rank: 30, team: 'Los Angeles Angels',     teamColor: C.Angels,       count: 6,  totalGames: 28, outcomes: buildOutcomes('over', 6,  ['under','under','push']) },
    ],
  },

  // ─── 2. Most Unders ───────────────────────────────────────────────────────
  {
    id: 'most-unders',
    label: 'Most Unders',
    countUnit: 'UNDERS',
    metaUnit: 'OUT OF 28 GAMES',
    rows: [
      { rank: 1,  team: 'St. Louis Cardinals',    teamColor: C.Cardinals,    count: 22, totalGames: 28, outcomes: buildOutcomes('under', 22, ['over','push','over']) },
      { rank: 2,  team: 'Seattle Mariners',       teamColor: C.Mariners,     count: 20, totalGames: 28, outcomes: buildOutcomes('under', 20, ['over','push','over','over']) },
      { rank: 3,  team: 'San Diego Padres',       teamColor: C.Padres,       count: 19, totalGames: 28, outcomes: buildOutcomes('under', 19, ['over','push']) },
      { rank: 4,  team: 'Minnesota Twins',        teamColor: C.Twins,        count: 18, totalGames: 28, outcomes: buildOutcomes('under', 18, ['over','over','push','over']) },
      { rank: 5,  team: 'San Francisco Giants',   teamColor: C.Giants,       count: 17, totalGames: 28, outcomes: buildOutcomes('under', 17, ['over','push','over']) },
      { rank: 6,  team: 'Chicago White Sox',      teamColor: C.WhiteSox,     count: 16, totalGames: 28, outcomes: buildOutcomes('under', 16, ['over','push','over']) },
      { rank: 7,  team: 'Colorado Rockies',       teamColor: C.Rockies,      count: 15, totalGames: 28, outcomes: buildOutcomes('under', 15, ['over','over','push']) },
      { rank: 8,  team: 'Oakland Athletics',      teamColor: C.Athletics,    count: 15, totalGames: 28, outcomes: buildOutcomes('under', 15, ['over','push','over']) },
      { rank: 9,  team: 'Detroit Tigers',         teamColor: C.Tigers,       count: 14, totalGames: 28, outcomes: buildOutcomes('under', 14, ['over','push','over']) },
      { rank: 10, team: 'Pittsburgh Pirates',     teamColor: C.Pirates,      count: 13, totalGames: 28, outcomes: buildOutcomes('under', 13, ['over','over','push']) },
      { rank: 11, team: 'Miami Marlins',          teamColor: C.Marlins,      count: 13, totalGames: 28, outcomes: buildOutcomes('under', 13, ['over','push','over']) },
      { rank: 12, team: 'Washington Nationals',   teamColor: C.Nationals,    count: 12, totalGames: 28, outcomes: buildOutcomes('under', 12, ['over','push']) },
      { rank: 13, team: 'Kansas City Royals',     teamColor: C.Royals,       count: 12, totalGames: 28, outcomes: buildOutcomes('under', 12, ['over','over','push']) },
      { rank: 14, team: 'Cincinnati Reds',        teamColor: C.Reds,         count: 11, totalGames: 28, outcomes: buildOutcomes('under', 11, ['over','push','over']) },
      { rank: 15, team: 'Texas Rangers',          teamColor: C.Rangers,      count: 11, totalGames: 28, outcomes: buildOutcomes('under', 11, ['over','over','push']) },
      { rank: 16, team: 'Milwaukee Brewers',      teamColor: C.Brewers,      count: 10, totalGames: 28, outcomes: buildOutcomes('under', 10, ['over','push','over']) },
      { rank: 17, team: 'Cleveland Guardians',    teamColor: C.Guardians,    count: 10, totalGames: 28, outcomes: buildOutcomes('under', 10, ['over','over','push']) },
      { rank: 18, team: 'Arizona Diamondbacks',   teamColor: C.Diamondbacks, count: 9,  totalGames: 28, outcomes: buildOutcomes('under', 9,  ['over','push','over']) },
      { rank: 19, team: 'Baltimore Orioles',      teamColor: C.Orioles,      count: 9,  totalGames: 28, outcomes: buildOutcomes('under', 9,  ['over','push']) },
      { rank: 20, team: 'Toronto Blue Jays',      teamColor: C.BlueJays,     count: 8,  totalGames: 28, outcomes: buildOutcomes('under', 8,  ['over','over','push']) },
      { rank: 21, team: 'New York Mets',          teamColor: C.Mets,         count: 8,  totalGames: 28, outcomes: buildOutcomes('under', 8,  ['over','push','over']) },
      { rank: 22, team: 'Houston Astros',         teamColor: C.Astros,       count: 7,  totalGames: 28, outcomes: buildOutcomes('under', 7,  ['over','over','push']) },
      { rank: 23, team: 'Chicago Cubs',           teamColor: C.Cubs,         count: 7,  totalGames: 28, outcomes: buildOutcomes('under', 7,  ['over','push','over']) },
      { rank: 24, team: 'Tampa Bay Rays',         teamColor: C.Rays,         count: 7,  totalGames: 28, outcomes: buildOutcomes('under', 7,  ['over','push']) },
      { rank: 25, team: 'Boston Red Sox',         teamColor: C.RedSox,       count: 6,  totalGames: 28, outcomes: buildOutcomes('under', 6,  ['over','over','push']) },
      { rank: 26, team: 'Philadelphia Phillies',  teamColor: C.Phillies,     count: 6,  totalGames: 28, outcomes: buildOutcomes('under', 6,  ['over','push','over']) },
      { rank: 27, team: 'Atlanta Braves',         teamColor: C.Braves,       count: 6,  totalGames: 28, outcomes: buildOutcomes('under', 6,  ['over','over','push']) },
      { rank: 28, team: 'New York Yankees',       teamColor: C.Yankees,      count: 6,  totalGames: 28, outcomes: buildOutcomes('under', 6,  ['over','push','over']) },
      { rank: 29, team: 'Los Angeles Dodgers',    teamColor: C.Dodgers,      count: 6,  totalGames: 28, outcomes: buildOutcomes('under', 6,  ['over','push']) },
      { rank: 30, team: 'Los Angeles Angels',     teamColor: C.Angels,       count: 6,  totalGames: 28, outcomes: buildOutcomes('under', 6,  ['over','over','push']) },
    ],
  },

  // ─── 3. Most ML Wins ──────────────────────────────────────────────────────
  {
    id: 'most-ml-wins',
    label: 'Most ML Wins',
    countUnit: 'ML WINS',
    metaUnit: 'OUT OF 28 GAMES',
    rows: [
      { rank: 1,  team: 'Boston Red Sox',         teamColor: C.RedSox,       count: 23, totalGames: 28, outcomes: buildOutcomes('win', 23, ['loss','push','loss']) },
      { rank: 2,  team: 'Chicago Cubs',           teamColor: C.Cubs,         count: 21, totalGames: 28, outcomes: buildOutcomes('win', 21, ['loss','loss','push']) },
      { rank: 3,  team: 'Houston Astros',         teamColor: C.Astros,       count: 20, totalGames: 28, outcomes: buildOutcomes('win', 20, ['loss','push','loss']) },
      { rank: 4,  team: 'Cleveland Guardians',    teamColor: C.Guardians,    count: 19, totalGames: 28, outcomes: buildOutcomes('win', 19, ['loss','push']) },
      { rank: 5,  team: 'Toronto Blue Jays',      teamColor: C.BlueJays,     count: 18, totalGames: 28, outcomes: buildOutcomes('win', 18, ['loss','push','loss','loss']) },
      { rank: 6,  team: 'Los Angeles Dodgers',    teamColor: C.Dodgers,      count: 17, totalGames: 28, outcomes: buildOutcomes('win', 17, ['loss','push','loss']) },
      { rank: 7,  team: 'Atlanta Braves',         teamColor: C.Braves,       count: 17, totalGames: 28, outcomes: buildOutcomes('win', 17, ['loss','loss','push']) },
      { rank: 8,  team: 'New York Yankees',       teamColor: C.Yankees,      count: 16, totalGames: 28, outcomes: buildOutcomes('win', 16, ['loss','push','loss']) },
      { rank: 9,  team: 'Philadelphia Phillies',  teamColor: C.Phillies,     count: 15, totalGames: 28, outcomes: buildOutcomes('win', 15, ['loss','loss','push']) },
      { rank: 10, team: 'Texas Rangers',          teamColor: C.Rangers,      count: 15, totalGames: 28, outcomes: buildOutcomes('win', 15, ['loss','push','loss']) },
      { rank: 11, team: 'Seattle Mariners',       teamColor: C.Mariners,     count: 14, totalGames: 28, outcomes: buildOutcomes('win', 14, ['loss','push','loss']) },
      { rank: 12, team: 'Tampa Bay Rays',         teamColor: C.Rays,         count: 14, totalGames: 28, outcomes: buildOutcomes('win', 14, ['loss','loss','push']) },
      { rank: 13, team: 'Milwaukee Brewers',      teamColor: C.Brewers,      count: 13, totalGames: 28, outcomes: buildOutcomes('win', 13, ['loss','push','loss']) },
      { rank: 14, team: 'Kansas City Royals',     teamColor: C.Royals,       count: 13, totalGames: 28, outcomes: buildOutcomes('win', 13, ['loss','loss','push']) },
      { rank: 15, team: 'Minnesota Twins',        teamColor: C.Twins,        count: 12, totalGames: 28, outcomes: buildOutcomes('win', 12, ['loss','push','loss']) },
      { rank: 16, team: 'Baltimore Orioles',      teamColor: C.Orioles,      count: 12, totalGames: 28, outcomes: buildOutcomes('win', 12, ['loss','loss','push']) },
      { rank: 17, team: 'San Francisco Giants',   teamColor: C.Giants,       count: 11, totalGames: 28, outcomes: buildOutcomes('win', 11, ['loss','push','loss']) },
      { rank: 18, team: 'San Diego Padres',       teamColor: C.Padres,       count: 11, totalGames: 28, outcomes: buildOutcomes('win', 11, ['loss','loss','push']) },
      { rank: 19, team: 'Arizona Diamondbacks',   teamColor: C.Diamondbacks, count: 10, totalGames: 28, outcomes: buildOutcomes('win', 10, ['loss','push','loss']) },
      { rank: 20, team: 'St. Louis Cardinals',    teamColor: C.Cardinals,    count: 10, totalGames: 28, outcomes: buildOutcomes('win', 10, ['loss','loss','push']) },
      { rank: 21, team: 'Detroit Tigers',         teamColor: C.Tigers,       count: 9,  totalGames: 28, outcomes: buildOutcomes('win', 9,  ['loss','push','loss']) },
      { rank: 22, team: 'Cincinnati Reds',        teamColor: C.Reds,         count: 9,  totalGames: 28, outcomes: buildOutcomes('win', 9,  ['loss','loss','push']) },
      { rank: 23, team: 'New York Mets',          teamColor: C.Mets,         count: 9,  totalGames: 28, outcomes: buildOutcomes('win', 9,  ['loss','push','loss']) },
      { rank: 24, team: 'Oakland Athletics',      teamColor: C.Athletics,    count: 8,  totalGames: 28, outcomes: buildOutcomes('win', 8,  ['loss','loss','push']) },
      { rank: 25, team: 'Pittsburgh Pirates',     teamColor: C.Pirates,      count: 8,  totalGames: 28, outcomes: buildOutcomes('win', 8,  ['loss','push','loss']) },
      { rank: 26, team: 'Washington Nationals',   teamColor: C.Nationals,    count: 8,  totalGames: 28, outcomes: buildOutcomes('win', 8,  ['loss','loss','push']) },
      { rank: 27, team: 'Colorado Rockies',       teamColor: C.Rockies,      count: 7,  totalGames: 28, outcomes: buildOutcomes('win', 7,  ['loss','push','loss']) },
      { rank: 28, team: 'Miami Marlins',          teamColor: C.Marlins,      count: 7,  totalGames: 28, outcomes: buildOutcomes('win', 7,  ['loss','loss','push']) },
      { rank: 29, team: 'Chicago White Sox',      teamColor: C.WhiteSox,     count: 7,  totalGames: 28, outcomes: buildOutcomes('win', 7,  ['loss','push','loss']) },
      { rank: 30, team: 'Los Angeles Angels',     teamColor: C.Angels,       count: 7,  totalGames: 28, outcomes: buildOutcomes('win', 7,  ['loss','loss','push']) },
    ],
  },

  // ─── 4. Most ML Losses ────────────────────────────────────────────────────
  {
    id: 'most-ml-losses',
    label: 'Most ML Losses',
    countUnit: 'ML LOSSES',
    metaUnit: 'OUT OF 28 GAMES',
    rows: [
      { rank: 1,  team: 'New York Mets',          teamColor: C.Mets,         count: 23, totalGames: 28, outcomes: buildOutcomes('loss', 23, ['win','push','win']) },
      { rank: 2,  team: 'Baltimore Orioles',       teamColor: C.Orioles,      count: 21, totalGames: 28, outcomes: buildOutcomes('loss', 21, ['win','win','push']) },
      { rank: 3,  team: 'Arizona Diamondbacks',    teamColor: C.Diamondbacks, count: 20, totalGames: 28, outcomes: buildOutcomes('loss', 20, ['win','push','win']) },
      { rank: 4,  team: 'Texas Rangers',           teamColor: C.Rangers,      count: 19, totalGames: 28, outcomes: buildOutcomes('loss', 19, ['win','push']) },
      { rank: 5,  team: 'Milwaukee Brewers',       teamColor: C.Brewers,      count: 18, totalGames: 28, outcomes: buildOutcomes('loss', 18, ['win','win','push','win']) },
      { rank: 6,  team: 'Colorado Rockies',        teamColor: C.Rockies,      count: 17, totalGames: 28, outcomes: buildOutcomes('loss', 17, ['win','push','win']) },
      { rank: 7,  team: 'Oakland Athletics',       teamColor: C.Athletics,    count: 17, totalGames: 28, outcomes: buildOutcomes('loss', 17, ['win','win','push']) },
      { rank: 8,  team: 'Chicago White Sox',       teamColor: C.WhiteSox,     count: 16, totalGames: 28, outcomes: buildOutcomes('loss', 16, ['win','push','win']) },
      { rank: 9,  team: 'Miami Marlins',           teamColor: C.Marlins,      count: 15, totalGames: 28, outcomes: buildOutcomes('loss', 15, ['win','win','push']) },
      { rank: 10, team: 'Pittsburgh Pirates',      teamColor: C.Pirates,      count: 15, totalGames: 28, outcomes: buildOutcomes('loss', 15, ['win','push','win']) },
      { rank: 11, team: 'Washington Nationals',    teamColor: C.Nationals,    count: 14, totalGames: 28, outcomes: buildOutcomes('loss', 14, ['win','push']) },
      { rank: 12, team: 'Kansas City Royals',      teamColor: C.Royals,       count: 14, totalGames: 28, outcomes: buildOutcomes('loss', 14, ['win','win','push']) },
      { rank: 13, team: 'Detroit Tigers',          teamColor: C.Tigers,       count: 13, totalGames: 28, outcomes: buildOutcomes('loss', 13, ['win','push','win']) },
      { rank: 14, team: 'Cincinnati Reds',         teamColor: C.Reds,         count: 13, totalGames: 28, outcomes: buildOutcomes('loss', 13, ['win','win','push']) },
      { rank: 15, team: 'Los Angeles Angels',      teamColor: C.Angels,       count: 12, totalGames: 28, outcomes: buildOutcomes('loss', 12, ['win','push','win']) },
      { rank: 16, team: 'San Diego Padres',        teamColor: C.Padres,       count: 12, totalGames: 28, outcomes: buildOutcomes('loss', 12, ['win','win','push']) },
      { rank: 17, team: 'Minnesota Twins',         teamColor: C.Twins,        count: 11, totalGames: 28, outcomes: buildOutcomes('loss', 11, ['win','push','win']) },
      { rank: 18, team: 'St. Louis Cardinals',     teamColor: C.Cardinals,    count: 11, totalGames: 28, outcomes: buildOutcomes('loss', 11, ['win','win','push']) },
      { rank: 19, team: 'San Francisco Giants',    teamColor: C.Giants,       count: 10, totalGames: 28, outcomes: buildOutcomes('loss', 10, ['win','push','win']) },
      { rank: 20, team: 'Cleveland Guardians',     teamColor: C.Guardians,    count: 10, totalGames: 28, outcomes: buildOutcomes('loss', 10, ['win','win','push']) },
      { rank: 21, team: 'Seattle Mariners',        teamColor: C.Mariners,     count: 9,  totalGames: 28, outcomes: buildOutcomes('loss', 9,  ['win','push','win']) },
      { rank: 22, team: 'Tampa Bay Rays',          teamColor: C.Rays,         count: 9,  totalGames: 28, outcomes: buildOutcomes('loss', 9,  ['win','win','push']) },
      { rank: 23, team: 'Philadelphia Phillies',   teamColor: C.Phillies,     count: 8,  totalGames: 28, outcomes: buildOutcomes('loss', 8,  ['win','push','win']) },
      { rank: 24, team: 'Toronto Blue Jays',       teamColor: C.BlueJays,     count: 8,  totalGames: 28, outcomes: buildOutcomes('loss', 8,  ['win','win','push']) },
      { rank: 25, team: 'Atlanta Braves',          teamColor: C.Braves,       count: 7,  totalGames: 28, outcomes: buildOutcomes('loss', 7,  ['win','push','win']) },
      { rank: 26, team: 'Houston Astros',          teamColor: C.Astros,       count: 7,  totalGames: 28, outcomes: buildOutcomes('loss', 7,  ['win','win','push']) },
      { rank: 27, team: 'Chicago Cubs',            teamColor: C.Cubs,         count: 7,  totalGames: 28, outcomes: buildOutcomes('loss', 7,  ['win','push','win']) },
      { rank: 28, team: 'New York Yankees',        teamColor: C.Yankees,      count: 7,  totalGames: 28, outcomes: buildOutcomes('loss', 7,  ['win','win','push']) },
      { rank: 29, team: 'Boston Red Sox',          teamColor: C.RedSox,       count: 7,  totalGames: 28, outcomes: buildOutcomes('loss', 7,  ['win','push','win']) },
      { rank: 30, team: 'Los Angeles Dodgers',     teamColor: C.Dodgers,      count: 7,  totalGames: 28, outcomes: buildOutcomes('loss', 7,  ['win','win','push']) },
    ],
  },

  // ─── 5. Most ATS Covers ───────────────────────────────────────────────────
  {
    id: 'most-ats-covers',
    label: 'Most ATS Covers',
    countUnit: 'COVERS',
    metaUnit: 'OUT OF 28 GAMES',
    rows: [
      { rank: 1,  team: 'Philadelphia Phillies',  teamColor: C.Phillies,     count: 20, totalGames: 28, outcomes: buildOutcomes('win', 20, ['loss','push','loss']) },
      { rank: 2,  team: 'New York Yankees',       teamColor: C.Yankees,      count: 18, totalGames: 28, outcomes: buildOutcomes('win', 18, ['loss','loss','push']) },
      { rank: 3,  team: 'Boston Red Sox',         teamColor: C.RedSox,       count: 17, totalGames: 28, outcomes: buildOutcomes('win', 17, ['loss','push','loss','loss']) },
      { rank: 4,  team: 'Atlanta Braves',         teamColor: C.Braves,       count: 16, totalGames: 28, outcomes: buildOutcomes('win', 16, ['loss','push']) },
      { rank: 5,  team: 'Los Angeles Dodgers',    teamColor: C.Dodgers,      count: 15, totalGames: 28, outcomes: buildOutcomes('win', 15, ['loss','push','loss']) },
      { rank: 6,  team: 'Houston Astros',         teamColor: C.Astros,       count: 15, totalGames: 28, outcomes: buildOutcomes('win', 15, ['loss','loss','push']) },
      { rank: 7,  team: 'Tampa Bay Rays',         teamColor: C.Rays,         count: 14, totalGames: 28, outcomes: buildOutcomes('win', 14, ['loss','push','loss']) },
      { rank: 8,  team: 'Chicago Cubs',           teamColor: C.Cubs,         count: 14, totalGames: 28, outcomes: buildOutcomes('win', 14, ['loss','loss','push']) },
      { rank: 9,  team: 'Seattle Mariners',       teamColor: C.Mariners,     count: 13, totalGames: 28, outcomes: buildOutcomes('win', 13, ['loss','push','loss']) },
      { rank: 10, team: 'Toronto Blue Jays',      teamColor: C.BlueJays,     count: 13, totalGames: 28, outcomes: buildOutcomes('win', 13, ['loss','loss','push']) },
      { rank: 11, team: 'Cleveland Guardians',    teamColor: C.Guardians,    count: 12, totalGames: 28, outcomes: buildOutcomes('win', 12, ['loss','push','loss']) },
      { rank: 12, team: 'Minnesota Twins',        teamColor: C.Twins,        count: 12, totalGames: 28, outcomes: buildOutcomes('win', 12, ['loss','loss','push']) },
      { rank: 13, team: 'Texas Rangers',          teamColor: C.Rangers,      count: 11, totalGames: 28, outcomes: buildOutcomes('win', 11, ['loss','push','loss']) },
      { rank: 14, team: 'Baltimore Orioles',      teamColor: C.Orioles,      count: 11, totalGames: 28, outcomes: buildOutcomes('win', 11, ['loss','loss','push']) },
      { rank: 15, team: 'San Diego Padres',       teamColor: C.Padres,       count: 10, totalGames: 28, outcomes: buildOutcomes('win', 10, ['loss','push','loss']) },
      { rank: 16, team: 'San Francisco Giants',   teamColor: C.Giants,       count: 10, totalGames: 28, outcomes: buildOutcomes('win', 10, ['loss','loss','push']) },
      { rank: 17, team: 'Kansas City Royals',     teamColor: C.Royals,       count: 9,  totalGames: 28, outcomes: buildOutcomes('win', 9,  ['loss','push','loss']) },
      { rank: 18, team: 'Milwaukee Brewers',      teamColor: C.Brewers,      count: 9,  totalGames: 28, outcomes: buildOutcomes('win', 9,  ['loss','loss','push']) },
      { rank: 19, team: 'Arizona Diamondbacks',   teamColor: C.Diamondbacks, count: 9,  totalGames: 28, outcomes: buildOutcomes('win', 9,  ['loss','push','loss']) },
      { rank: 20, team: 'St. Louis Cardinals',    teamColor: C.Cardinals,    count: 8,  totalGames: 28, outcomes: buildOutcomes('win', 8,  ['loss','loss','push']) },
      { rank: 21, team: 'Cincinnati Reds',        teamColor: C.Reds,         count: 8,  totalGames: 28, outcomes: buildOutcomes('win', 8,  ['loss','push','loss']) },
      { rank: 22, team: 'New York Mets',          teamColor: C.Mets,         count: 8,  totalGames: 28, outcomes: buildOutcomes('win', 8,  ['loss','loss','push']) },
      { rank: 23, team: 'Oakland Athletics',      teamColor: C.Athletics,    count: 7,  totalGames: 28, outcomes: buildOutcomes('win', 7,  ['loss','push','loss']) },
      { rank: 24, team: 'Detroit Tigers',         teamColor: C.Tigers,       count: 7,  totalGames: 28, outcomes: buildOutcomes('win', 7,  ['loss','loss','push']) },
      { rank: 25, team: 'Pittsburgh Pirates',     teamColor: C.Pirates,      count: 7,  totalGames: 28, outcomes: buildOutcomes('win', 7,  ['loss','push','loss']) },
      { rank: 26, team: 'Washington Nationals',   teamColor: C.Nationals,    count: 7,  totalGames: 28, outcomes: buildOutcomes('win', 7,  ['loss','loss','push']) },
      { rank: 27, team: 'Colorado Rockies',       teamColor: C.Rockies,      count: 7,  totalGames: 28, outcomes: buildOutcomes('win', 7,  ['loss','push','loss']) },
      { rank: 28, team: 'Miami Marlins',          teamColor: C.Marlins,      count: 7,  totalGames: 28, outcomes: buildOutcomes('win', 7,  ['loss','loss','push']) },
      { rank: 29, team: 'Chicago White Sox',      teamColor: C.WhiteSox,     count: 7,  totalGames: 28, outcomes: buildOutcomes('win', 7,  ['loss','push','loss']) },
      { rank: 30, team: 'Los Angeles Angels',     teamColor: C.Angels,       count: 7,  totalGames: 28, outcomes: buildOutcomes('win', 7,  ['loss','loss','push']) },
    ],
  },

  // ─── 6. Most ATS Losses ───────────────────────────────────────────────────
  {
    id: 'most-ats-losses',
    label: 'Most ATS Losses',
    countUnit: 'ATS LOSSES',
    metaUnit: 'OUT OF 28 GAMES',
    rows: [
      { rank: 1,  team: 'Chicago Cubs',           teamColor: C.Cubs,         count: 20, totalGames: 28, outcomes: buildOutcomes('loss', 20, ['win','push','win']) },
      { rank: 2,  team: 'St. Louis Cardinals',    teamColor: C.Cardinals,    count: 18, totalGames: 28, outcomes: buildOutcomes('loss', 18, ['win','win','push']) },
      { rank: 3,  team: 'Minnesota Twins',        teamColor: C.Twins,        count: 17, totalGames: 28, outcomes: buildOutcomes('loss', 17, ['win','push','win']) },
      { rank: 4,  team: 'New York Mets',          teamColor: C.Mets,         count: 16, totalGames: 28, outcomes: buildOutcomes('loss', 16, ['win','push']) },
      { rank: 5,  team: 'San Francisco Giants',   teamColor: C.Giants,       count: 15, totalGames: 28, outcomes: buildOutcomes('loss', 15, ['win','win','push','win']) },
      { rank: 6,  team: 'Colorado Rockies',       teamColor: C.Rockies,      count: 14, totalGames: 28, outcomes: buildOutcomes('loss', 14, ['win','push','win']) },
      { rank: 7,  team: 'Oakland Athletics',      teamColor: C.Athletics,    count: 14, totalGames: 28, outcomes: buildOutcomes('loss', 14, ['win','win','push']) },
      { rank: 8,  team: 'Chicago White Sox',      teamColor: C.WhiteSox,     count: 13, totalGames: 28, outcomes: buildOutcomes('loss', 13, ['win','push','win']) },
      { rank: 9,  team: 'Miami Marlins',          teamColor: C.Marlins,      count: 13, totalGames: 28, outcomes: buildOutcomes('loss', 13, ['win','win','push']) },
      { rank: 10, team: 'Pittsburgh Pirates',     teamColor: C.Pirates,      count: 12, totalGames: 28, outcomes: buildOutcomes('loss', 12, ['win','push','win']) },
      { rank: 11, team: 'Washington Nationals',   teamColor: C.Nationals,    count: 12, totalGames: 28, outcomes: buildOutcomes('loss', 12, ['win','win','push']) },
      { rank: 12, team: 'Kansas City Royals',     teamColor: C.Royals,       count: 11, totalGames: 28, outcomes: buildOutcomes('loss', 11, ['win','push','win']) },
      { rank: 13, team: 'Detroit Tigers',         teamColor: C.Tigers,       count: 11, totalGames: 28, outcomes: buildOutcomes('loss', 11, ['win','win','push']) },
      { rank: 14, team: 'Cincinnati Reds',        teamColor: C.Reds,         count: 10, totalGames: 28, outcomes: buildOutcomes('loss', 10, ['win','push','win']) },
      { rank: 15, team: 'Los Angeles Angels',     teamColor: C.Angels,       count: 10, totalGames: 28, outcomes: buildOutcomes('loss', 10, ['win','win','push']) },
      { rank: 16, team: 'San Diego Padres',       teamColor: C.Padres,       count: 9,  totalGames: 28, outcomes: buildOutcomes('loss', 9,  ['win','push','win']) },
      { rank: 17, team: 'Arizona Diamondbacks',   teamColor: C.Diamondbacks, count: 9,  totalGames: 28, outcomes: buildOutcomes('loss', 9,  ['win','win','push']) },
      { rank: 18, team: 'Milwaukee Brewers',      teamColor: C.Brewers,      count: 9,  totalGames: 28, outcomes: buildOutcomes('loss', 9,  ['win','push','win']) },
      { rank: 19, team: 'Baltimore Orioles',      teamColor: C.Orioles,      count: 8,  totalGames: 28, outcomes: buildOutcomes('loss', 8,  ['win','win','push']) },
      { rank: 20, team: 'Cleveland Guardians',    teamColor: C.Guardians,    count: 8,  totalGames: 28, outcomes: buildOutcomes('loss', 8,  ['win','push','win']) },
      { rank: 21, team: 'Texas Rangers',          teamColor: C.Rangers,      count: 8,  totalGames: 28, outcomes: buildOutcomes('loss', 8,  ['win','win','push']) },
      { rank: 22, team: 'Seattle Mariners',       teamColor: C.Mariners,     count: 7,  totalGames: 28, outcomes: buildOutcomes('loss', 7,  ['win','push','win']) },
      { rank: 23, team: 'Tampa Bay Rays',         teamColor: C.Rays,         count: 7,  totalGames: 28, outcomes: buildOutcomes('loss', 7,  ['win','win','push']) },
      { rank: 24, team: 'Toronto Blue Jays',      teamColor: C.BlueJays,     count: 7,  totalGames: 28, outcomes: buildOutcomes('loss', 7,  ['win','push','win']) },
      { rank: 25, team: 'Houston Astros',         teamColor: C.Astros,       count: 7,  totalGames: 28, outcomes: buildOutcomes('loss', 7,  ['win','win','push']) },
      { rank: 26, team: 'Atlanta Braves',         teamColor: C.Braves,       count: 7,  totalGames: 28, outcomes: buildOutcomes('loss', 7,  ['win','push','win']) },
      { rank: 27, team: 'Boston Red Sox',         teamColor: C.RedSox,       count: 7,  totalGames: 28, outcomes: buildOutcomes('loss', 7,  ['win','win','push']) },
      { rank: 28, team: 'New York Yankees',       teamColor: C.Yankees,      count: 7,  totalGames: 28, outcomes: buildOutcomes('loss', 7,  ['win','push','win']) },
      { rank: 29, team: 'Los Angeles Dodgers',    teamColor: C.Dodgers,      count: 7,  totalGames: 28, outcomes: buildOutcomes('loss', 7,  ['win','win','push']) },
      { rank: 30, team: 'Philadelphia Phillies',  teamColor: C.Phillies,     count: 7,  totalGames: 28, outcomes: buildOutcomes('loss', 7,  ['win','push','win']) },
    ],
  },

  // ─── 7. Most Pushes ───────────────────────────────────────────────────────
  {
    id: 'most-pushes',
    label: 'Most Pushes',
    countUnit: 'PUSHES',
    metaUnit: 'OUT OF 28 GAMES',
    rows: [
      { rank: 1,  team: 'San Diego Padres',       teamColor: C.Padres,       count: 6, totalGames: 28, outcomes: buildOutcomes('push', 6, ['win','loss','over','under','win','loss']) },
      { rank: 2,  team: 'New York Yankees',       teamColor: C.Yankees,      count: 5, totalGames: 28, outcomes: buildOutcomes('push', 5, ['win','loss','win','over','under']) },
      { rank: 3,  team: 'Tampa Bay Rays',         teamColor: C.Rays,         count: 4, totalGames: 28, outcomes: buildOutcomes('push', 4, ['win','over','loss','under','win','loss']) },
      { rank: 4,  team: 'Cleveland Guardians',    teamColor: C.Guardians,    count: 3, totalGames: 28, outcomes: buildOutcomes('push', 3, ['win','loss','over','win','under','loss','win']) },
      { rank: 5,  team: 'Milwaukee Brewers',      teamColor: C.Brewers,      count: 3, totalGames: 28, outcomes: buildOutcomes('push', 3, ['win','loss','over','under','win','loss']) },
      { rank: 6,  team: 'Boston Red Sox',         teamColor: C.RedSox,       count: 2, totalGames: 28, outcomes: buildOutcomes('push', 2, ['win','loss','win','over','loss','under','win','loss']) },
      { rank: 7,  team: 'Houston Astros',         teamColor: C.Astros,       count: 2, totalGames: 28, outcomes: buildOutcomes('push', 2, ['win','loss','over','win','under','loss']) },
      { rank: 8,  team: 'Atlanta Braves',         teamColor: C.Braves,       count: 2, totalGames: 28, outcomes: buildOutcomes('push', 2, ['win','loss','win','over','under','loss']) },
      { rank: 9,  team: 'Minnesota Twins',        teamColor: C.Twins,        count: 2, totalGames: 28, outcomes: buildOutcomes('push', 2, ['win','over','loss','under','win','loss']) },
      { rank: 10, team: 'Seattle Mariners',       teamColor: C.Mariners,     count: 2, totalGames: 28, outcomes: buildOutcomes('push', 2, ['under','loss','over','win','loss','win']) },
      { rank: 11, team: 'Philadelphia Phillies',  teamColor: C.Phillies,     count: 2, totalGames: 28, outcomes: buildOutcomes('push', 2, ['win','loss','over','under','win','loss']) },
      { rank: 12, team: 'Kansas City Royals',     teamColor: C.Royals,       count: 1, totalGames: 28, outcomes: buildOutcomes('push', 1, ['win','loss','over','win','under','loss','win']) },
      { rank: 13, team: 'Toronto Blue Jays',      teamColor: C.BlueJays,     count: 1, totalGames: 28, outcomes: buildOutcomes('push', 1, ['win','over','loss','win','under','loss']) },
      { rank: 14, team: 'Los Angeles Dodgers',    teamColor: C.Dodgers,      count: 1, totalGames: 28, outcomes: buildOutcomes('push', 1, ['win','loss','over','under','win','loss']) },
      { rank: 15, team: 'St. Louis Cardinals',    teamColor: C.Cardinals,    count: 1, totalGames: 28, outcomes: buildOutcomes('push', 1, ['under','loss','over','win','loss','win']) },
      { rank: 16, team: 'Texas Rangers',          teamColor: C.Rangers,      count: 1, totalGames: 28, outcomes: buildOutcomes('push', 1, ['win','loss','win','over','under','loss']) },
      { rank: 17, team: 'Baltimore Orioles',      teamColor: C.Orioles,      count: 1, totalGames: 28, outcomes: buildOutcomes('push', 1, ['win','over','loss','under','win','loss']) },
      { rank: 18, team: 'Arizona Diamondbacks',   teamColor: C.Diamondbacks, count: 1, totalGames: 28, outcomes: buildOutcomes('push', 1, ['loss','win','over','win','under','loss']) },
      { rank: 19, team: 'San Francisco Giants',   teamColor: C.Giants,       count: 1, totalGames: 28, outcomes: buildOutcomes('push', 1, ['win','loss','over','under','win','loss']) },
      { rank: 20, team: 'Chicago Cubs',           teamColor: C.Cubs,         count: 1, totalGames: 28, outcomes: buildOutcomes('push', 1, ['loss','over','win','under','loss','win']) },
      { rank: 21, team: 'New York Mets',          teamColor: C.Mets,         count: 0, totalGames: 28, outcomes: buildEmpty(['win','loss','over','under']) },
      { rank: 21, team: 'Detroit Tigers',         teamColor: C.Tigers,       count: 0, totalGames: 28, outcomes: buildEmpty(['loss','win','under','over']) },
      { rank: 21, team: 'Cincinnati Reds',        teamColor: C.Reds,         count: 0, totalGames: 28, outcomes: buildEmpty(['win','loss','over','under']) },
      { rank: 21, team: 'Oakland Athletics',      teamColor: C.Athletics,    count: 0, totalGames: 28, outcomes: buildEmpty(['loss','over','win','under']) },
      { rank: 21, team: 'Pittsburgh Pirates',     teamColor: C.Pirates,      count: 0, totalGames: 28, outcomes: buildEmpty(['win','under','loss','over']) },
      { rank: 21, team: 'Washington Nationals',   teamColor: C.Nationals,    count: 0, totalGames: 28, outcomes: buildEmpty(['loss','win','over','under']) },
      { rank: 21, team: 'Colorado Rockies',       teamColor: C.Rockies,      count: 0, totalGames: 28, outcomes: buildEmpty(['win','loss','under','over']) },
      { rank: 21, team: 'Miami Marlins',          teamColor: C.Marlins,      count: 0, totalGames: 28, outcomes: buildEmpty(['loss','over','under','win']) },
      { rank: 21, team: 'Chicago White Sox',      teamColor: C.WhiteSox,     count: 0, totalGames: 28, outcomes: buildEmpty(['win','loss','over','under']) },
      { rank: 21, team: 'Los Angeles Angels',     teamColor: C.Angels,       count: 0, totalGames: 28, outcomes: buildEmpty(['under','win','loss','over']) },
    ],
  },

  // ─── 8. Most Home Wins ────────────────────────────────────────────────────
  {
    id: 'most-home-wins',
    label: 'Most Home Wins',
    countUnit: 'HOME WINS',
    metaUnit: 'OUT OF 28 GAMES',
    rows: [
      { rank: 1,  team: 'Houston Astros',         teamColor: C.Astros,       count: 13, totalGames: 28, outcomes: buildOutcomes('win', 13, ['none','none','none','loss','none']) },
      { rank: 2,  team: 'Los Angeles Dodgers',    teamColor: C.Dodgers,      count: 12, totalGames: 28, outcomes: buildOutcomes('win', 12, ['none','none','loss','none','none']) },
      { rank: 3,  team: 'Atlanta Braves',         teamColor: C.Braves,       count: 11, totalGames: 28, outcomes: buildOutcomes('win', 11, ['none','none','none','loss','none']) },
      { rank: 4,  team: 'St. Louis Cardinals',    teamColor: C.Cardinals,    count: 11, totalGames: 28, outcomes: buildOutcomes('win', 11, ['none','none','loss','none','none']) },
      { rank: 5,  team: 'Toronto Blue Jays',      teamColor: C.BlueJays,     count: 10, totalGames: 28, outcomes: buildOutcomes('win', 10, ['none','none','loss','none']) },
      { rank: 6,  team: 'Seattle Mariners',       teamColor: C.Mariners,     count: 10, totalGames: 28, outcomes: buildOutcomes('win', 10, ['none','none','none','loss','none','none']) },
      { rank: 7,  team: 'Boston Red Sox',         teamColor: C.RedSox,       count: 9,  totalGames: 28, outcomes: buildOutcomes('win', 9,  ['none','none','loss','none']) },
      { rank: 8,  team: 'New York Yankees',       teamColor: C.Yankees,      count: 9,  totalGames: 28, outcomes: buildOutcomes('win', 9,  ['none','none','none','loss','none']) },
      { rank: 9,  team: 'Philadelphia Phillies',  teamColor: C.Phillies,     count: 8,  totalGames: 28, outcomes: buildOutcomes('win', 8,  ['none','none','loss','none','none']) },
      { rank: 10, team: 'Tampa Bay Rays',         teamColor: C.Rays,         count: 8,  totalGames: 28, outcomes: buildOutcomes('win', 8,  ['none','none','none','loss','none']) },
      { rank: 11, team: 'Chicago Cubs',           teamColor: C.Cubs,         count: 8,  totalGames: 28, outcomes: buildOutcomes('win', 8,  ['none','loss','none','none','none']) },
      { rank: 12, team: 'Cleveland Guardians',    teamColor: C.Guardians,    count: 7,  totalGames: 28, outcomes: buildOutcomes('win', 7,  ['none','none','loss','none']) },
      { rank: 13, team: 'Minnesota Twins',        teamColor: C.Twins,        count: 7,  totalGames: 28, outcomes: buildOutcomes('win', 7,  ['none','none','none','loss','none']) },
      { rank: 14, team: 'Kansas City Royals',     teamColor: C.Royals,       count: 7,  totalGames: 28, outcomes: buildOutcomes('win', 7,  ['none','loss','none','none']) },
      { rank: 15, team: 'Texas Rangers',          teamColor: C.Rangers,      count: 6,  totalGames: 28, outcomes: buildOutcomes('win', 6,  ['none','none','loss','none','none']) },
      { rank: 16, team: 'Milwaukee Brewers',      teamColor: C.Brewers,      count: 6,  totalGames: 28, outcomes: buildOutcomes('win', 6,  ['none','none','none','loss','none']) },
      { rank: 17, team: 'Baltimore Orioles',      teamColor: C.Orioles,      count: 6,  totalGames: 28, outcomes: buildOutcomes('win', 6,  ['none','loss','none','none','none']) },
      { rank: 18, team: 'San Diego Padres',       teamColor: C.Padres,       count: 6,  totalGames: 28, outcomes: buildOutcomes('win', 6,  ['none','none','loss','none']) },
      { rank: 19, team: 'San Francisco Giants',   teamColor: C.Giants,       count: 5,  totalGames: 28, outcomes: buildOutcomes('win', 5,  ['none','none','none','loss','none']) },
      { rank: 20, team: 'Arizona Diamondbacks',   teamColor: C.Diamondbacks, count: 5,  totalGames: 28, outcomes: buildOutcomes('win', 5,  ['none','loss','none','none']) },
      { rank: 21, team: 'Detroit Tigers',         teamColor: C.Tigers,       count: 5,  totalGames: 28, outcomes: buildOutcomes('win', 5,  ['none','none','loss','none','none']) },
      { rank: 22, team: 'Cincinnati Reds',        teamColor: C.Reds,         count: 4,  totalGames: 28, outcomes: buildOutcomes('win', 4,  ['none','none','none','loss','none']) },
      { rank: 23, team: 'New York Mets',          teamColor: C.Mets,         count: 4,  totalGames: 28, outcomes: buildOutcomes('win', 4,  ['none','loss','none','none']) },
      { rank: 24, team: 'Oakland Athletics',      teamColor: C.Athletics,    count: 4,  totalGames: 28, outcomes: buildOutcomes('win', 4,  ['none','none','loss','none']) },
      { rank: 25, team: 'Pittsburgh Pirates',     teamColor: C.Pirates,      count: 4,  totalGames: 28, outcomes: buildOutcomes('win', 4,  ['none','none','none','loss','none']) },
      { rank: 26, team: 'Washington Nationals',   teamColor: C.Nationals,    count: 3,  totalGames: 28, outcomes: buildOutcomes('win', 3,  ['none','loss','none','none','none']) },
      { rank: 27, team: 'Colorado Rockies',       teamColor: C.Rockies,      count: 3,  totalGames: 28, outcomes: buildOutcomes('win', 3,  ['none','none','loss','none']) },
      { rank: 28, team: 'Miami Marlins',          teamColor: C.Marlins,      count: 3,  totalGames: 28, outcomes: buildOutcomes('win', 3,  ['none','none','none','loss','none']) },
      { rank: 29, team: 'Chicago White Sox',      teamColor: C.WhiteSox,     count: 3,  totalGames: 28, outcomes: buildOutcomes('win', 3,  ['none','loss','none','none']) },
      { rank: 30, team: 'Los Angeles Angels',     teamColor: C.Angels,       count: 3,  totalGames: 28, outcomes: buildOutcomes('win', 3,  ['none','none','loss','none','none']) },
    ],
  },

  // ─── 9. Most Away Wins ────────────────────────────────────────────────────
  {
    id: 'most-away-wins',
    label: 'Most Away Wins',
    countUnit: 'AWAY WINS',
    metaUnit: 'OUT OF 28 GAMES',
    rows: [
      { rank: 1,  team: 'Texas Rangers',          teamColor: C.Rangers,      count: 13, totalGames: 28, outcomes: buildOutcomes('win', 13, ['none','none','none','loss','none']) },
      { rank: 2,  team: 'Atlanta Braves',         teamColor: C.Braves,       count: 12, totalGames: 28, outcomes: buildOutcomes('win', 12, ['none','none','loss','none','none']) },
      { rank: 3,  team: 'Arizona Diamondbacks',   teamColor: C.Diamondbacks, count: 11, totalGames: 28, outcomes: buildOutcomes('win', 11, ['none','none','none','loss','none']) },
      { rank: 4,  team: 'Boston Red Sox',         teamColor: C.RedSox,       count: 10, totalGames: 28, outcomes: buildOutcomes('win', 10, ['none','none','loss','none','none']) },
      { rank: 5,  team: 'Minnesota Twins',        teamColor: C.Twins,        count: 10, totalGames: 28, outcomes: buildOutcomes('win', 10, ['none','none','none','loss','none']) },
      { rank: 6,  team: 'New York Yankees',       teamColor: C.Yankees,      count: 9,  totalGames: 28, outcomes: buildOutcomes('win', 9,  ['none','loss','none','none']) },
      { rank: 7,  team: 'Los Angeles Dodgers',    teamColor: C.Dodgers,      count: 9,  totalGames: 28, outcomes: buildOutcomes('win', 9,  ['none','none','loss','none','none']) },
      { rank: 8,  team: 'Philadelphia Phillies',  teamColor: C.Phillies,     count: 8,  totalGames: 28, outcomes: buildOutcomes('win', 8,  ['none','none','none','loss','none']) },
      { rank: 9,  team: 'Tampa Bay Rays',         teamColor: C.Rays,         count: 8,  totalGames: 28, outcomes: buildOutcomes('win', 8,  ['none','loss','none','none','none']) },
      { rank: 10, team: 'Chicago Cubs',           teamColor: C.Cubs,         count: 8,  totalGames: 28, outcomes: buildOutcomes('win', 8,  ['none','none','loss','none']) },
      { rank: 11, team: 'Seattle Mariners',       teamColor: C.Mariners,     count: 7,  totalGames: 28, outcomes: buildOutcomes('win', 7,  ['none','none','none','loss','none']) },
      { rank: 12, team: 'Houston Astros',         teamColor: C.Astros,       count: 7,  totalGames: 28, outcomes: buildOutcomes('win', 7,  ['none','loss','none','none']) },
      { rank: 13, team: 'Toronto Blue Jays',      teamColor: C.BlueJays,     count: 7,  totalGames: 28, outcomes: buildOutcomes('win', 7,  ['none','none','loss','none','none']) },
      { rank: 14, team: 'Cleveland Guardians',    teamColor: C.Guardians,    count: 6,  totalGames: 28, outcomes: buildOutcomes('win', 6,  ['none','none','none','loss','none']) },
      { rank: 15, team: 'Milwaukee Brewers',      teamColor: C.Brewers,      count: 6,  totalGames: 28, outcomes: buildOutcomes('win', 6,  ['none','loss','none','none']) },
      { rank: 16, team: 'Kansas City Royals',     teamColor: C.Royals,       count: 6,  totalGames: 28, outcomes: buildOutcomes('win', 6,  ['none','none','loss','none']) },
      { rank: 17, team: 'Baltimore Orioles',      teamColor: C.Orioles,      count: 5,  totalGames: 28, outcomes: buildOutcomes('win', 5,  ['none','none','none','loss','none']) },
      { rank: 18, team: 'St. Louis Cardinals',    teamColor: C.Cardinals,    count: 5,  totalGames: 28, outcomes: buildOutcomes('win', 5,  ['none','loss','none','none','none']) },
      { rank: 19, team: 'San Francisco Giants',   teamColor: C.Giants,       count: 5,  totalGames: 28, outcomes: buildOutcomes('win', 5,  ['none','none','loss','none']) },
      { rank: 20, team: 'San Diego Padres',       teamColor: C.Padres,       count: 5,  totalGames: 28, outcomes: buildOutcomes('win', 5,  ['none','none','none','loss','none']) },
      { rank: 21, team: 'New York Mets',          teamColor: C.Mets,         count: 4,  totalGames: 28, outcomes: buildOutcomes('win', 4,  ['none','loss','none','none']) },
      { rank: 22, team: 'Detroit Tigers',         teamColor: C.Tigers,       count: 4,  totalGames: 28, outcomes: buildOutcomes('win', 4,  ['none','none','loss','none','none']) },
      { rank: 23, team: 'Cincinnati Reds',        teamColor: C.Reds,         count: 4,  totalGames: 28, outcomes: buildOutcomes('win', 4,  ['none','none','none','loss','none']) },
      { rank: 24, team: 'Oakland Athletics',      teamColor: C.Athletics,    count: 4,  totalGames: 28, outcomes: buildOutcomes('win', 4,  ['none','loss','none','none']) },
      { rank: 25, team: 'Pittsburgh Pirates',     teamColor: C.Pirates,      count: 3,  totalGames: 28, outcomes: buildOutcomes('win', 3,  ['none','none','loss','none','none']) },
      { rank: 26, team: 'Washington Nationals',   teamColor: C.Nationals,    count: 3,  totalGames: 28, outcomes: buildOutcomes('win', 3,  ['none','none','none','loss','none']) },
      { rank: 27, team: 'Colorado Rockies',       teamColor: C.Rockies,      count: 3,  totalGames: 28, outcomes: buildOutcomes('win', 3,  ['none','loss','none','none']) },
      { rank: 28, team: 'Miami Marlins',          teamColor: C.Marlins,      count: 3,  totalGames: 28, outcomes: buildOutcomes('win', 3,  ['none','none','loss','none']) },
      { rank: 29, team: 'Chicago White Sox',      teamColor: C.WhiteSox,     count: 3,  totalGames: 28, outcomes: buildOutcomes('win', 3,  ['none','none','none','loss','none']) },
      { rank: 30, team: 'Los Angeles Angels',     teamColor: C.Angels,       count: 3,  totalGames: 28, outcomes: buildOutcomes('win', 3,  ['none','loss','none','none','none']) },
    ],
  },

  // ─── 10. Most Bonus Outcomes ──────────────────────────────────────────────
  {
    id: 'most-bonus',
    label: 'Most Bonus Outcomes',
    countUnit: 'BONUS',
    metaUnit: 'BONUS HITS',
    rows: [
      { rank: 1,  team: 'Baltimore Orioles',      teamColor: C.Orioles,      count: 8, totalGames: 28, outcomes: buildOutcomes('bonus', 8,  ['over','win','under','loss','win','over']) },
      { rank: 2,  team: 'Tampa Bay Rays',         teamColor: C.Rays,         count: 7, totalGames: 28, outcomes: buildOutcomes('bonus', 7,  ['win','over','loss','under','win','loss']) },
      { rank: 3,  team: 'San Francisco Giants',   teamColor: C.Giants,       count: 6, totalGames: 28, outcomes: buildOutcomes('bonus', 6,  ['over','under','win','loss','win']) },
      { rank: 4,  team: 'New York Mets',          teamColor: C.Mets,         count: 5, totalGames: 28, outcomes: buildOutcomes('bonus', 5,  ['win','over','loss','under','win','loss','over']) },
      { rank: 5,  team: 'Philadelphia Phillies',  teamColor: C.Phillies,     count: 5, totalGames: 28, outcomes: buildOutcomes('bonus', 5,  ['win','loss','over','win','under','loss','win','over']) },
      { rank: 6,  team: 'Los Angeles Dodgers',    teamColor: C.Dodgers,      count: 4, totalGames: 28, outcomes: buildOutcomes('bonus', 4,  ['over','win','loss','under','win']) },
      { rank: 7,  team: 'Atlanta Braves',         teamColor: C.Braves,       count: 4, totalGames: 28, outcomes: buildOutcomes('bonus', 4,  ['win','loss','over','under','win']) },
      { rank: 8,  team: 'Boston Red Sox',         teamColor: C.RedSox,       count: 3, totalGames: 28, outcomes: buildOutcomes('bonus', 3,  ['win','over','loss','win','under','loss']) },
      { rank: 9,  team: 'Houston Astros',         teamColor: C.Astros,       count: 3, totalGames: 28, outcomes: buildOutcomes('bonus', 3,  ['over','win','loss','under','win']) },
      { rank: 10, team: 'Chicago Cubs',           teamColor: C.Cubs,         count: 3, totalGames: 28, outcomes: buildOutcomes('bonus', 3,  ['win','loss','over','win','under','loss']) },
      { rank: 11, team: 'New York Yankees',       teamColor: C.Yankees,      count: 2, totalGames: 28, outcomes: buildOutcomes('bonus', 2,  ['win','loss','over','under','win','loss']) },
      { rank: 12, team: 'Texas Rangers',          teamColor: C.Rangers,      count: 2, totalGames: 28, outcomes: buildOutcomes('bonus', 2,  ['over','win','loss','under','win','loss']) },
      { rank: 13, team: 'Seattle Mariners',       teamColor: C.Mariners,     count: 2, totalGames: 28, outcomes: buildOutcomes('bonus', 2,  ['win','over','loss','win','under']) },
      { rank: 14, team: 'Minnesota Twins',        teamColor: C.Twins,        count: 2, totalGames: 28, outcomes: buildOutcomes('bonus', 2,  ['loss','win','over','under','win']) },
      { rank: 15, team: 'Cleveland Guardians',    teamColor: C.Guardians,    count: 1, totalGames: 28, outcomes: buildOutcomes('bonus', 1,  ['win','loss','over','win','under','loss','win']) },
      { rank: 16, team: 'Toronto Blue Jays',      teamColor: C.BlueJays,     count: 1, totalGames: 28, outcomes: buildOutcomes('bonus', 1,  ['over','win','loss','under','win']) },
      { rank: 17, team: 'Milwaukee Brewers',      teamColor: C.Brewers,      count: 1, totalGames: 28, outcomes: buildOutcomes('bonus', 1,  ['win','loss','win','over','under','loss']) },
      { rank: 18, team: 'Arizona Diamondbacks',   teamColor: C.Diamondbacks, count: 1, totalGames: 28, outcomes: buildOutcomes('bonus', 1,  ['loss','win','over','win','under','loss']) },
      { rank: 19, team: 'St. Louis Cardinals',    teamColor: C.Cardinals,    count: 1, totalGames: 28, outcomes: buildOutcomes('bonus', 1,  ['over','under','win','loss','win']) },
      { rank: 20, team: 'San Diego Padres',       teamColor: C.Padres,       count: 1, totalGames: 28, outcomes: buildOutcomes('bonus', 1,  ['win','loss','over','win','under']) },
      { rank: 21, team: 'Kansas City Royals',     teamColor: C.Royals,       count: 0, totalGames: 28, outcomes: buildEmpty(['win','loss','over','under']) },
      { rank: 21, team: 'Detroit Tigers',         teamColor: C.Tigers,       count: 0, totalGames: 28, outcomes: buildEmpty(['loss','win','under','over']) },
      { rank: 21, team: 'Cincinnati Reds',        teamColor: C.Reds,         count: 0, totalGames: 28, outcomes: buildEmpty(['win','loss','over','under']) },
      { rank: 21, team: 'Oakland Athletics',      teamColor: C.Athletics,    count: 0, totalGames: 28, outcomes: buildEmpty(['loss','over','win','under']) },
      { rank: 21, team: 'Pittsburgh Pirates',     teamColor: C.Pirates,      count: 0, totalGames: 28, outcomes: buildEmpty(['win','under','loss','over']) },
      { rank: 21, team: 'Washington Nationals',   teamColor: C.Nationals,    count: 0, totalGames: 28, outcomes: buildEmpty(['loss','win','over','under']) },
      { rank: 21, team: 'Colorado Rockies',       teamColor: C.Rockies,      count: 0, totalGames: 28, outcomes: buildEmpty(['win','loss','under','over']) },
      { rank: 21, team: 'Miami Marlins',          teamColor: C.Marlins,      count: 0, totalGames: 28, outcomes: buildEmpty(['loss','over','under','win']) },
      { rank: 21, team: 'Chicago White Sox',      teamColor: C.WhiteSox,     count: 0, totalGames: 28, outcomes: buildEmpty(['win','loss','over','under']) },
      { rank: 21, team: 'Los Angeles Angels',     teamColor: C.Angels,       count: 0, totalGames: 28, outcomes: buildEmpty(['under','win','loss','over']) },
    ],
  },
]
